### ISSUE TITLE
How do I do any of this crap? 

### ISSUE THREAD

**Issue by Akira4712** [Amuyea-gbatemp/Shin-Megami-Tensei-V-Save-Editor#3]
How do I do a pip install PyQt5?
I want to use the save editor but I can't unless this pip install PyQt5.
SMT4 and SMT4A save editors didn't require this crap.
I have 0 knowledge on coding. And Yet the author of this program expects me to know how to do all this coding stuff.
Frankly coding is so very confusing to me.
Figuring this out is giving me a headache. 
Please respond.

**Comment by Amuyea-gbatemp** [comment]
I'm not forcing you to use this. There are other save editors that use C# and one is on switch console 🙂 

There are tutorials and you could google if you wanted to.
